services:
    nginx:
        image: ghcr.io/php-ug/nginx:latest
        build:
            context: .docker/nginx
            dockerfile: Dockerfile
        volumes:
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/php.ug
        ports:
            - 80:80
            - 443:443
        links:
            - php:php
    php:
        image: ghcr.io/php-ug/php:latest
        build:
            context: .docker/php
            dockerfile: Dockerfile
        env_file:
            -   .env
        links:
            -   smtp:smtp
    node:
        image: node:20
        volumes:
            - .:/app
        working_dir: /app

