services:
    php:
        volumes:
            -   .:/var/www/html

    nginx:
        volumes:
            -   .:/var/www/html
    smtp:
        image: mailhog/mailhog
        ports:
            - 8025:8025
