services:
    nginx:
        build:
            context: .docker/nginx
            dockerfile: Dockerfile
        volumes:
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/php.ug
        ports:
            - 80:80
            - 443:443
        links:
            - php:php
    php:
        build:
            context: .docker/php
            dockerfile: Dockerfile
        image: php-ug:latest
        env_file:
            -   .env
        links:
            -   smtp:smtp
    node:
        image: node:20
        volumes:
            - .:/app
        working_dir: /app
    smtp:
        image: mailhog/mailhog
        ports:
            - 8025:8025
